# Use the official Nginx image as a base
FROM nginx:latest

# Copy the custom nginx configuration file from the nginx directory
# into the container at the correct path.
COPY nginx.conf /etc/nginx/nginx.conf
